apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: observability
type: Opaque
stringData:
    slack_api_url: https://hooks.slack.com/services/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