apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - alertmanager-configmap.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
  - thanos-sidecar-configmap.yaml
  - prometheus-service-monitor.yaml
  - prometheus-service.yaml
  - prometheus-deployment.yaml
