# path: argocd/applications/monitoring.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    # opentelemetry-operator(sync-wave: "0") 이후에 실행되도록 설정
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/minina0407/portfogram-manifest.git
    path: apps/monitoring/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      # CRD가 없을 때 dry-run 스킵
      - SkipDryRunOnMissingResource=true
      # Server-side apply로 대규모 리소스 동기화 성능 개선
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
