apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: portfogram:argoproj.io/Application:argocd/redis
  creationTimestamp: "2026-02-10T11:45:30Z"
  generation: 4
  name: redis
  namespace: argocd
  resourceVersion: "11752"
  uid: f14ce3d7-6fe2-4f38-a565-3ae7678f0a9e
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/redis/overlays/dev
    repoURL: https://github.com/minina0407/portfogram-manifest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-02-10T11:45:31Z"
    status: Healthy
  reconciledAt: "2026-02-10T11:48:19Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: redis-config-9dm786ttk6
    namespace: redis
    status: Synced
    version: v1
  - kind: Service
    name: redis
    namespace: redis
    status: Synced
    version: v1
  - group: apps
    kind: StatefulSet
    name: redis
    namespace: redis
    status: Synced
    version: v1
  sourceType: Kustomize
  summary:
    images:
    - redis:latest
  sync:
    comparedTo:
      destination:
        namespace: redis
        server: https://kubernetes.default.svc
      source:
        path: apps/redis/overlays/dev
        repoURL: https://github.com/minina0407/portfogram-manifest.git
        targetRevision: HEAD
    revision: b8e54b95969f3e5138dc230aa89a1f8ee41b85e3
    status: Synced
