apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: portfogram:argoproj.io/Application:argocd/spring-boot
  name: spring-boot
  namespace: argocd
spec:
  destination:
    namespace: portfogram
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: apps/spring-boot
    repoURL: https://github.com/minina0407/portfogram-manifest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
