# path: argocd/applications/spring-boot.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minina0407/portfogram-manifest.git
    targetRevision: HEAD
    path: apps/spring-boot
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portfogram
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
