apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    # Let's Encrypt Staging 환경 (rate limit이 없음)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: minina1868@gmail.com
    # ACME 계정의 private key를 저장할 Secret 참조
    privateKeySecretRef:
      name: letsencrypt-dev-account-key
    # ACME HTTP-01 challenge를 위한 solver
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt Production 환경
    server: https://acme-v02.api.letsencrypt.org/directory
    email: minina1868@gmail.com
    # ACME 계정의 private key를 저장할 Secret 참조
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    # ACME HTTP-01 challenge를 위한 solver
    solvers:
    - http01:
        ingress:
          class: nginx

